[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = "cancun"

[profile.default.fmt]
line_length = 100

[rpc_endpoints]
arc_testnet = "${ARC_RPC_URL:-https://rpc.testnet.arc.network}"
